# Generated by Django 3.2.12 on 2024-06-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6),
        ),
    ]
